# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1105, 695)
        font = QtGui.QFont()
        font.setPointSize(28)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("body {background-color: coral;}")
        self.centralwidget.setObjectName("centralwidget")
        self.img_logo = QtWidgets.QLabel(self.centralwidget)
        self.img_logo.setGeometry(QtCore.QRect(780, 30, 291, 91))
        self.img_logo.setMaximumSize(QtCore.QSize(421, 113))
        self.img_logo.setStyleSheet("\n"
"  width: 100%;\n"
"  height: auto;\n"
"")
        self.img_logo.setText("")
        self.img_logo.setPixmap(QtGui.QPixmap("../../../trial1/images/imgLeadingEdge.png"))
        self.img_logo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.img_logo.setIndent(0)
        self.img_logo.setObjectName("img_logo")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 330, 1121, 121))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(80, 570, 121, 41))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../../../trial1/images/imgDots.png"))
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(80, 500, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: white;\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.btn_help = QtWidgets.QPushButton(self.centralwidget)
        self.btn_help.setGeometry(QtCore.QRect(0, 20, 121, 71))
        self.btn_help.setStyleSheet("border:none;")
        self.btn_help.setObjectName("btn_help")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1105, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Therbo Robotic Therapy"))
        self.pushButton.setText(_translate("MainWindow", "Manual Mode"))
        self.btn_help.setText(_translate("MainWindow", "Button"))
